<?php

/**
 * @file
 * The code for the SMED feeder feature and to manage it.
 */

/**
 * Returns the list options for the status field (c4m_user_status).
 *
 * @return array
 *   An array with key|label.
 */
function c4m_smed_feeder_field_status_list_options() {
  module_load_include('inc', 'c4m_smed_feeder', 'c4m_smed_feeder.statuses');

  $options = [];
  foreach (c4m_smed_feeder_status_list() as $key => $item) {
    $options[$key] = $item['label'];
  }
  return $options;
}
